//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalDocumentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Who_know = new HashSet<Who_know>();
        }
    
        public int Id { get; set; }
        public string Index { get; set; }
        public string Name { get; set; }
        public int Doc_tipe_id { get; set; }
        public System.DateTime Validity_period { get; set; }
        public int Save_place_id { get; set; }
        public int Developer_id { get; set; }
        public System.DateTime Date_order { get; set; }
        public string Number_order { get; set; }
        public bool Relevance { get; set; }
        public string Doc_file { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Doc_tipe Doc_tipe { get; set; }
        public virtual Save_place Save_place { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Who_know> Who_know { get; set; }
    }
}
