//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalDocumentation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Who_know
    {
        public int Id { get; set; }
        public int Document_id { get; set; }
        public int Departmen_id { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Document Document { get; set; }
    }
}
